In [4]:
#import necessary libraries
import pandas as pd
import re
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [9]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [33]:
train_df=pd.read_csv('train.csv')

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159571 entries, 0 to 159570
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             159571 non-null  object
 1   comment_text   159571 non-null  object
 2   toxic          159571 non-null  int64
 3   severe_toxic   159571 non-null  int64
 4   obscene        159571 non-null  int64
 5   threat         159571 non-null  int64
 6   insult         159571 non-null  int64
 7   identity_hate  159571 non-null  int64
dtypes: int64(6), object(2)
memory usage: 9.7+ MB

In [ ]:
train_df

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0

In [34]:
train_df.comment_text.values[0]

"Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27"

In [35]:
target_cols = ['toxic','severe_toxic','obscene','threat','insult','identity_hate'] #list of target columns

In [36]:
# looking at the distribution of target columns
for col in target_cols:
    print(train_df[col].value_counts(normalize=True))

toxic
0    0.904156
1    0.095844
Name: proportion, dtype: float64
severe_toxic
0    0.990004
1    0.009996
Name: proportion, dtype: float64
obscene
0    0.947052
1    0.052948
Name: proportion, dtype: float64
threat
0    0.997004
1    0.002996
Name: proportion, dtype: float64
insult
0    0.950636
1    0.049364
Name: proportion, dtype: float64
identity_hate
0    0.991195
1    0.008805
Name: proportion, dtype: float64

In [ ]:
# Text preprocessing function
def preprocess_text(text):
    # Remove special characters and punctuation
    text = re.sub(r'[^\w\s]', '', text)
    # Convert to lowercase
    text = text.lower()
    # Tokenize text
    tokens = word_tokenize(text)
    # Remove stopwords
    tokens = [word for word in tokens if word not in stopwords.words('english')]
    # Join tokens back into a string
    processed_text = ' '.join(tokens)
    return processed_text

# Apply preprocessing to the 'text' column
train_df['clean_text'] = train_df['comment_text'].apply(preprocess_text)

In [10]:
from torchtext.data.utils import get_tokenizer

In [ ]:
!pip install torchtext

Collecting torchtext
  Downloading torchtext-0.18.0-cp310-cp310-manylinux1_x86_64.whl.metadata (7.9 kB)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.10/site-packages (from torchtext) (4.65.0)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from torchtext) (2.31.0)
Collecting torch>=2.3.0 (from torchtext)
  Downloading torch-2.3.0-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from torchtext) (1.26.2)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch>=2.3.0->torchtext) (3.13.1)
Collecting typing-extensions>=4.8.0 (from torch>=2.3.0->torchtext)
  Downloading typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch>=2.3.0->torchtext) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch>=2.3.0->torchtext) (3.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch>=2.3.0->torchtext) (3.1.2)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch>=2.3.0->torchtext) (2023.12.2)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch>=2.3.0->torchtext)
  Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch>=2.3.0->torchtext)
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch>=2.3.0->torchtext)
  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch>=2.3.0->torchtext)
  Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch>=2.3.0->torchtext)
  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch>=2.3.0->torchtext)
  Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch>=2.3.0->torchtext)
  Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch>=2.3.0->torchtext)
  Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch>=2.3.0->torchtext)
  Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch>=2.3.0->torchtext)
  Downloading nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch>=2.3.0->torchtext)
  Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.3.0 (from torch>=2.3.0->torchtext)
  Downloading triton-2.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch>=2.3.0->torchtext)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->torchtext) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->torchtext) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->torchtext) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->torchtext) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch>=2.3.0->torchtext) (2.1.1)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch>=2.3.0->torchtext) (1.3.0)
Downloading torchtext-0.18.0-cp310-cp310-manylinux1_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 29.4 MB/s eta 0:00:0000:0100:01
Downloading torch-2.3.0-cp310-cp310-manylinux1_x86_64.whl (779.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 779.1/779.1 MB 6.7 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 15.8 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 48.6 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 47.9 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 38.0 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 10.1 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 32.3 MB/s eta 0:00:0000:0100:01
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 47.3 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 31.7 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 28.3 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.2/176.2 MB 29.8 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 11.3 MB/s eta 0:00:00
Downloading triton-2.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (168.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.1/168.1 MB 29.5 MB/s eta 0:00:0000:0100:01
Downloading typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 52.4 MB/s eta 0:00:0000:0100:01
Installing collected packages: typing-extensions, triton, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, torch, torchtext
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.7.1
    Uninstalling typing_extensions-4.7.1:
      Successfully uninstalled typing_extensions-4.7.1
  Attempting uninstall: triton
    Found existing installation: triton 2.1.0
    Uninstalling triton-2.1.0:
      Successfully uninstalled triton-2.1.0
  Attempting uninstall: torch
    Found existing installation: torch 2.1.2
    Uninstalling torch-2.1.2:
      Successfully uninstalled torch-2.1.2
Successfully installed nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.1.105 torch-2.3.0 torchtext-0.18.0 triton-2.3.0 typing-extensions-4.11.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [11]:
tokenizer = get_tokenizer('basic_english')

In [37]:
sample_text = train_df.comment_text.values[1]
sample_text

"D'aww! He matches this background colour I'm seemingly stuck with. Thanks.  (talk) 21:51, January 11, 2016 (UTC)"

In [ ]:
sample_tokens = tokenizer(sample_text)[:20] # lower case , individual words
sample_tokens

['d',
 "'",
 'aww',
 '!',
 'he',
 'matches',
 'this',
 'background',
 'colour',
 'i',
 "'",
 'm',
 'seemingly',
 'stuck',
 'with',
 '.',
 'thanks',
 '.',
 '(',
 'talk']

In [38]:
from torchtext.vocab import build_vocab_from_iterator

In [39]:
VOCAB_SIZE = 1500
unknown_token = '<unk>'
pad_token = '<pad>'

In [40]:
comment_tokens = train_df.comment_text.map(tokenizer)

In [41]:
vocab = build_vocab_from_iterator(comment_tokens,
                                  specials = [unknown_token,pad_token],
                                  max_tokens = VOCAB_SIZE) # assigns a number to tokens

In [42]:
vocab['it']

14

In [43]:
vocab[unknown_token] , vocab[pad_token]

(0, 1)

In [44]:
vocab.set_default_index(vocab[unknown_token])

In [45]:
vocab['background']

1443

In [ ]:
!pip install matplotlib

Requirement already satisfied: matplotlib in /opt/conda/lib/python3.10/site-packages (3.8.4)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.21 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (1.26.2)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (23.1)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (10.0.1)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [13]:
# function to truncate sentences excedding max_length or pad when length is less than max_length

def pad_tokens(tokens):
    if len(tokens) > MAX_LENGTH:
        return tokens[:MAX_LENGTH]
    else:
        return tokens + [pad_token] * (MAX_LENGTH - len(tokens))

In [14]:
# example of the functions
MAX_LENGTH = 5
# truncation
test1 = 'I am doing good, how are you?'
print(pad_tokens(tokenizer(test1)))

['i', 'am', 'doing', 'good', ',']

In [15]:
# padding
test1 = "I'm good"
print(pad_tokens(tokenizer(test1)))

['i', "'", 'm', 'good', '<pad>']

In [16]:
MAX_LENGTH = 150

In [17]:
import torch
from torch.utils.data import Dataset

In [ ]:
train_df.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate', 'clean_text'],
      dtype='object')

In [18]:
class Jigsaw(Dataset):
    def __init__(self , df , test_dataset=False):
        super().__init__()
        self.df = df
        self.test_dataset = test_dataset

    def __getitem__(self,index):
        comment_text = self.df.comment_text.values[index]
        comment_tokens = pad_tokens(tokenizer(comment_text))
        input = torch.tensor(vocab.lookup_indices(comment_tokens))
        if self.test_dataset:
            target = torch.tensor([0,0,0,0,0,0]).float() # for test dataset make the target as all zeros , which is not in use
        else:
            target = torch.tensor(self.df[target_cols].values[index]).float()
        return input , target

    def __len__(self):
        return len(self.df)

In [ ]:
train_dataset = Jigsaw(train_df)

In [ ]:
train_dataset[2]

(tensor([406, 439,   4,   6,   9,  81, 145,  19, 257,   5,  86, 330,   2,  14,
           9,  28,  61,  13,  18, 594,  12,   0, 486, 496, 111,   8, 596,   5,
          46, 328, 140, 360,   7,  39,  50,  38,   2,  59, 212,   5, 426,  69,
          47,   3,   0, 102,   3, 704, 482,   2,   1,   1,   1,   1,   1,   1,
           1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
           1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
           1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
           1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
           1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
           1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
           1,   1,   1,   1,   1,   1,   1,   1,   1,   1]),
 tensor([0., 0., 0., 0., 0., 0.]))

In [ ]:
from torch.utils.data import random_split

In [ ]:
validation_fraction = 0.25

In [ ]:
train_ds , val_ds = random_split(train_dataset, [1-validation_fraction, validation_fraction])

In [61]:
test_df=pd.read_csv('test.csv')

In [62]:
test_df

                      id                                       comment_text
0       00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1       0000247867823ef7  == From RfC == \n\n The title is fine as it is...
2       00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3       00017563c3f7919a  :If you have a look back at the source, the in...
4       00017695ad8997eb          I don't anonymously edit articles at all.
...                  ...                                                ...
153159  fffcd0960ee309b5  . \n i totally agree, this stuff is nothing bu...
153160  fffd7a9a6eb32c16  == Throw from out field to home plate. == \n\n...
153161  fffda9e8d6fafa9e  " \n\n == Okinotorishima categories == \n\n I ...
153162  fffe8f1340a79fc2  " \n\n == ""One of the founding nations of the...
153163  ffffce3fb183ee80  " \n :::Stop already. Your bullshit is not wel...

[153164 rows x 2 columns]

In [63]:
test_dataset = Jigsaw(test_df,test_dataset=True)

In [22]:
from torch.utils.data import DataLoader

In [ ]:
BATCH_SIZE = 128

train_dl = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=4, pin_memory=True)
val_dl = DataLoader(val_ds, batch_size=BATCH_SIZE*2, num_workers=4, pin_memory=True)
test_dl = DataLoader(test_dataset, batch_size=BATCH_SIZE*2, num_workers=4, pin_memory=True)

In [ ]:
for a_input , a_target in train_dl:
    print(a_input.shape)
    print(a_target.shape)
    break

torch.Size([128, 150])
torch.Size([128, 6])

In [27]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [28]:
class LSTMModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim):
        super().__init__()
        self.emb = nn.Embedding(vocab_size, embedding_dim, padding_idx=1)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, batch_first=True)
        self.fc1 = nn.Linear(hidden_dim, 6)
        self.learning_rate = 0.01
        self.criterion = nn.BCEWithLogitsLoss()

    def forward(self, x):
        out = self.emb(x)
        out, _ = self.lstm(out)
        out = F.relu(out[:, -1, :])
        out = self.fc1(out)
        return out

    def training_step(self, batch, batch_idx):
        inputs, targets = batch
        outputs = self(inputs)
        loss = self.criterion(outputs, targets)
        return loss

    def validation_step(self, batch, batch_idx):
        inputs, targets = batch
        outputs = self(inputs)
        loss = self.criterion(outputs, targets)
        return loss.item()

    def validation_epoch_end(self, validation_step_outputs):
        loss = np.mean(validation_step_outputs)
        print("Epoch #{}; Loss: {:4f} ".format(self.current_epoch, loss))

    def predict_step(self, batch, batch_idx):
        inputs, _ = batch
        outputs = self(inputs)
        probs = torch.sigmoid(outputs)
        return probs

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=self.learning_rate)

In [29]:
model = LSTMModel(vocab_size=VOCAB_SIZE, embedding_dim=256, hidden_dim=128)

In [ ]:
for batch in train_dl:
    b_inputs, b_targets = batch
    print('b_input.shape', b_inputs.shape)
    print('b_targets.shape', b_targets.shape)

    outputs = model(b_inputs)
    print('outputs.shape', outputs.shape)

    # Calculate probabilities using sigmoid activation
    probs = torch.sigmoid(outputs)

    # Calculate the loss using BCEWithLogitsLoss
    loss = model.criterion(outputs, b_targets)
    print('Loss', loss.item())
    break

b_input.shape torch.Size([128, 150])
b_targets.shape torch.Size([128, 6])
outputs.shape torch.Size([128, 6])
Loss 0.6864359974861145

In [47]:
# Move model to GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

LSTMModel(
  (emb): Embedding(1500, 256, padding_idx=1)
  (lstm): LSTM(256, 128, batch_first=True)
  (fc1): Linear(in_features=128, out_features=6, bias=True)
  (criterion): BCEWithLogitsLoss()
)

In [ ]:
# Define the optimizer (using a dummy learning rate for now)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
# Train your model using the defined optimizer and criterion for 3 epochs
for epoch in range(10):
    model.train()  # Set model to training mode
    for batch in train_dl:
        # Move data to GPU if available
        inputs, targets = batch[0].to(device), batch[1].to(device)

        # Forward pass
        outputs = model(inputs)

        # Calculate probabilities using sigmoid activation
        probs = torch.sigmoid(outputs)

        # Calculate the loss using BCEWithLogitsLoss
        loss = model.criterion(outputs, targets)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        print('Epoch [{}/{}], Batch Loss: {:.4f}'.format(epoch+1, 3, loss.item()))

    # Validate your model after each epoch
    model.eval()  # Set model to evaluation mode
    total_loss = 0
    with torch.no_grad():
        for batch in val_dl:
            # Move data to GPU if available
            inputs, targets = batch[0].to(device), batch[1].to(device)

            # Forward pass
            outputs = model(inputs)

            # Calculate probabilities using sigmoid activation
            probs = torch.sigmoid(outputs)

            # Calculate the loss using BCEWithLogitsLoss
            loss = model.criterion(outputs, targets)

            # Accumulate validation loss
            total_loss += loss.item() * inputs.size(0)

    # Calculate average validation loss for the epoch
    avg_val_loss = total_loss / len(val_ds)
    print(f"Epoch {epoch + 1}/{3}, Validation Loss: {avg_val_loss:.4f}")

Epoch [1/3], Batch Loss: 0.6865
Epoch [1/3], Batch Loss: 0.6813
Epoch [1/3], Batch Loss: 0.6774
Epoch [1/3], Batch Loss: 0.6713
Epoch [1/3], Batch Loss: 0.6687
Epoch [1/3], Batch Loss: 0.6624
Epoch [1/3], Batch Loss: 0.6594
Epoch [1/3], Batch Loss: 0.6548
Epoch [1/3], Batch Loss: 0.6501
Epoch [1/3], Batch Loss: 0.6357
Epoch [1/3], Batch Loss: 0.6286
Epoch [1/3], Batch Loss: 0.6296
Epoch [1/3], Batch Loss: 0.6162
Epoch [1/3], Batch Loss: 0.6066
Epoch [1/3], Batch Loss: 0.5907
Epoch [1/3], Batch Loss: 0.5609
Epoch [1/3], Batch Loss: 0.5066
Epoch [1/3], Batch Loss: 0.4648
Epoch [1/3], Batch Loss: 0.4258
Epoch [1/3], Batch Loss: 0.3737
Epoch [1/3], Batch Loss: 0.3450
Epoch [1/3], Batch Loss: 0.3048
Epoch [1/3], Batch Loss: 0.3033
Epoch [1/3], Batch Loss: 0.2752
Epoch [1/3], Batch Loss: 0.2794
Epoch [1/3], Batch Loss: 0.2704
Epoch [1/3], Batch Loss: 0.2342
Epoch [1/3], Batch Loss: 0.2541
Epoch [1/3], Batch Loss: 0.2102
Epoch [1/3], Batch Loss: 0.2252
Epoch [1/3], Batch Loss: 0.2283
Epoch [1/3], Batch Loss: 0.2173
Epoch [1/3], Batch Loss: 0.1940
Epoch [1/3], Batch Loss: 0.1908
Epoch [1/3], Batch Loss: 0.1638
Epoch [1/3], Batch Loss: 0.1844
Epoch [1/3], Batch Loss: 0.1360
Epoch [1/3], Batch Loss: 0.1612
Epoch [1/3], Batch Loss: 0.1467
Epoch [1/3], Batch Loss: 0.1709
Epoch [1/3], Batch Loss: 0.2021
Epoch [1/3], Batch Loss: 0.1780
Epoch [1/3], Batch Loss: 0.1381
Epoch [1/3], Batch Loss: 0.1410
Epoch [1/3], Batch Loss: 0.1065
Epoch [1/3], Batch Loss: 0.1829
Epoch [1/3], Batch Loss: 0.1587
Epoch [1/3], Batch Loss: 0.1086
Epoch [1/3], Batch Loss: 0.1446
Epoch [1/3], Batch Loss: 0.1218
Epoch [1/3], Batch Loss: 0.2606
Epoch [1/3], Batch Loss: 0.2160
Epoch [1/3], Batch Loss: 0.1367
Epoch [1/3], Batch Loss: 0.1594
Epoch [1/3], Batch Loss: 0.1652
Epoch [1/3], Batch Loss: 0.1408
Epoch [1/3], Batch Loss: 0.1080
Epoch [1/3], Batch Loss: 0.1388
Epoch [1/3], Batch Loss: 0.1427
Epoch [1/3], Batch Loss: 0.1733
Epoch [1/3], Batch Loss: 0.1345
Epoch [1/3], Batch Loss: 0.1029
Epoch [1/3], Batch Loss: 0.1556
Epoch [1/3], Batch Loss: 0.1857
Epoch [1/3], Batch Loss: 0.1473
Epoch [1/3], Batch Loss: 0.1224
Epoch [1/3], Batch Loss: 0.1452
Epoch [1/3], Batch Loss: 0.1120
Epoch [1/3], Batch Loss: 0.1365
Epoch [1/3], Batch Loss: 0.1289
Epoch [1/3], Batch Loss: 0.1699
Epoch [1/3], Batch Loss: 0.0921
Epoch [1/3], Batch Loss: 0.1202
Epoch [1/3], Batch Loss: 0.1285
Epoch [1/3], Batch Loss: 0.1012
Epoch [1/3], Batch Loss: 0.2109
Epoch [1/3], Batch Loss: 0.1045
Epoch [1/3], Batch Loss: 0.1833
Epoch [1/3], Batch Loss: 0.1067
Epoch [1/3], Batch Loss: 0.1563
Epoch [1/3], Batch Loss: 0.1992
Epoch [1/3], Batch Loss: 0.1996
Epoch [1/3], Batch Loss: 0.1095
Epoch [1/3], Batch Loss: 0.0835
Epoch [1/3], Batch Loss: 0.1525
Epoch [1/3], Batch Loss: 0.1667
Epoch [1/3], Batch Loss: 0.1204
Epoch [1/3], Batch Loss: 0.1845
Epoch [1/3], Batch Loss: 0.1594
Epoch [1/3], Batch Loss: 0.1364
Epoch [1/3], Batch Loss: 0.2140
Epoch [1/3], Batch Loss: 0.1546
Epoch [1/3], Batch Loss: 0.0802
Epoch [1/3], Batch Loss: 0.1382
Epoch [1/3], Batch Loss: 0.1501
Epoch [1/3], Batch Loss: 0.1785
Epoch [1/3], Batch Loss: 0.1516
Epoch [1/3], Batch Loss: 0.1053
Epoch [1/3], Batch Loss: 0.1029
Epoch [1/3], Batch Loss: 0.1861
Epoch [1/3], Batch Loss: 0.2034
Epoch [1/3], Batch Loss: 0.1071
Epoch [1/3], Batch Loss: 0.1712
Epoch [1/3], Batch Loss: 0.1529
Epoch [1/3], Batch Loss: 0.1938
Epoch [1/3], Batch Loss: 0.1694
Epoch [1/3], Batch Loss: 0.1596
Epoch [1/3], Batch Loss: 0.1270
Epoch [1/3], Batch Loss: 0.1780
Epoch [1/3], Batch Loss: 0.1655
Epoch [1/3], Batch Loss: 0.1726
Epoch [1/3], Batch Loss: 0.1590
Epoch [1/3], Batch Loss: 0.1759
Epoch [1/3], Batch Loss: 0.1818
Epoch [1/3], Batch Loss: 0.1538
Epoch [1/3], Batch Loss: 0.1471
Epoch [1/3], Batch Loss: 0.0672
Epoch [1/3], Batch Loss: 0.1392
Epoch [1/3], Batch Loss: 0.1079
Epoch [1/3], Batch Loss: 0.1220
Epoch [1/3], Batch Loss: 0.1541
Epoch [1/3], Batch Loss: 0.0836
Epoch [1/3], Batch Loss: 0.1578
Epoch [1/3], Batch Loss: 0.1514
Epoch [1/3], Batch Loss: 0.1480
Epoch [1/3], Batch Loss: 0.1587
Epoch [1/3], Batch Loss: 0.1556
Epoch [1/3], Batch Loss: 0.1418
Epoch [1/3], Batch Loss: 0.1124
Epoch [1/3], Batch Loss: 0.1358
Epoch [1/3], Batch Loss: 0.1557
Epoch [1/3], Batch Loss: 0.1990
Epoch [1/3], Batch Loss: 0.1108
Epoch [1/3], Batch Loss: 0.1433
Epoch [1/3], Batch Loss: 0.1809
Epoch [1/3], Batch Loss: 0.0943
Epoch [1/3], Batch Loss: 0.1730
Epoch [1/3], Batch Loss: 0.1285
Epoch [1/3], Batch Loss: 0.1308
Epoch [1/3], Batch Loss: 0.1276
Epoch [1/3], Batch Loss: 0.1568
Epoch [1/3], Batch Loss: 0.1421
Epoch [1/3], Batch Loss: 0.1133
Epoch [1/3], Batch Loss: 0.0777
Epoch [1/3], Batch Loss: 0.1091
Epoch [1/3], Batch Loss: 0.1477
Epoch [1/3], Batch Loss: 0.1179
Epoch [1/3], Batch Loss: 0.2599
Epoch [1/3], Batch Loss: 0.1694
Epoch [1/3], Batch Loss: 0.1438
Epoch [1/3], Batch Loss: 0.1117
Epoch [1/3], Batch Loss: 0.1378
Epoch [1/3], Batch Loss: 0.1352
Epoch [1/3], Batch Loss: 0.1288
Epoch [1/3], Batch Loss: 0.1330
Epoch [1/3], Batch Loss: 0.1236
Epoch [1/3], Batch Loss: 0.1522
Epoch [1/3], Batch Loss: 0.1582
Epoch [1/3], Batch Loss: 0.1611
Epoch [1/3], Batch Loss: 0.0916
Epoch [1/3], Batch Loss: 0.1012
Epoch [1/3], Batch Loss: 0.1823
Epoch [1/3], Batch Loss: 0.1122
Epoch [1/3], Batch Loss: 0.1344
Epoch [1/3], Batch Loss: 0.0932
Epoch [1/3], Batch Loss: 0.2004
Epoch [1/3], Batch Loss: 0.1003
Epoch [1/3], Batch Loss: 0.1132
Epoch [1/3], Batch Loss: 0.1419
Epoch [1/3], Batch Loss: 0.1349
Epoch [1/3], Batch Loss: 0.1306
Epoch [1/3], Batch Loss: 0.1064
Epoch [1/3], Batch Loss: 0.1181
Epoch [1/3], Batch Loss: 0.0918
Epoch [1/3], Batch Loss: 0.1326
Epoch [1/3], Batch Loss: 0.1074
Epoch [1/3], Batch Loss: 0.0907
Epoch [1/3], Batch Loss: 0.1485
Epoch [1/3], Batch Loss: 0.1443
Epoch [1/3], Batch Loss: 0.1402
Epoch [1/3], Batch Loss: 0.2315
Epoch [1/3], Batch Loss: 0.1887
Epoch [1/3], Batch Loss: 0.1694
Epoch [1/3], Batch Loss: 0.1455
Epoch [1/3], Batch Loss: 0.2437
Epoch [1/3], Batch Loss: 0.1757
Epoch [1/3], Batch Loss: 0.1400
Epoch [1/3], Batch Loss: 0.1232
Epoch [1/3], Batch Loss: 0.1432
Epoch [1/3], Batch Loss: 0.1514
Epoch [1/3], Batch Loss: 0.1362
Epoch [1/3], Batch Loss: 0.1344
Epoch [1/3], Batch Loss: 0.1462
Epoch [1/3], Batch Loss: 0.1345
Epoch [1/3], Batch Loss: 0.1223
Epoch [1/3], Batch Loss: 0.1611
Epoch [1/3], Batch Loss: 0.2273
Epoch [1/3], Batch Loss: 0.1351
Epoch [1/3], Batch Loss: 0.1239
Epoch [1/3], Batch Loss: 0.1503
Epoch [1/3], Batch Loss: 0.1178
Epoch [1/3], Batch Loss: 0.0945
Epoch [1/3], Batch Loss: 0.0792
Epoch [1/3], Batch Loss: 0.1444
Epoch [1/3], Batch Loss: 0.1096
Epoch [1/3], Batch Loss: 0.1791
Epoch [1/3], Batch Loss: 0.1317
Epoch [1/3], Batch Loss: 0.0722
Epoch [1/3], Batch Loss: 0.0962
Epoch [1/3], Batch Loss: 0.1053
Epoch [1/3], Batch Loss: 0.1197
Epoch [1/3], Batch Loss: 0.1706
Epoch [1/3], Batch Loss: 0.1040
Epoch [1/3], Batch Loss: 0.1198
Epoch [1/3], Batch Loss: 0.1510
Epoch [1/3], Batch Loss: 0.1293
Epoch [1/3], Batch Loss: 0.1207
Epoch [1/3], Batch Loss: 0.1856
Epoch [1/3], Batch Loss: 0.1257
Epoch [1/3], Batch Loss: 0.1303
Epoch [1/3], Batch Loss: 0.1188
Epoch [1/3], Batch Loss: 0.1465
Epoch [1/3], Batch Loss: 0.1152
Epoch [1/3], Batch Loss: 0.1904
Epoch [1/3], Batch Loss: 0.1439
Epoch [1/3], Batch Loss: 0.1340
Epoch [1/3], Batch Loss: 0.1276
Epoch [1/3], Batch Loss: 0.1251
Epoch [1/3], Batch Loss: 0.1524
Epoch [1/3], Batch Loss: 0.1600
Epoch [1/3], Batch Loss: 0.1476
Epoch [1/3], Batch Loss: 0.1242
Epoch [1/3], Batch Loss: 0.0959
Epoch [1/3], Batch Loss: 0.1142
Epoch [1/3], Batch Loss: 0.1384
Epoch [1/3], Batch Loss: 0.1066
Epoch [1/3], Batch Loss: 0.1541
Epoch [1/3], Batch Loss: 0.1550
Epoch [1/3], Batch Loss: 0.1286
Epoch [1/3], Batch Loss: 0.1658
Epoch [1/3], Batch Loss: 0.1949
Epoch [1/3], Batch Loss: 0.1443
Epoch [1/3], Batch Loss: 0.1126
Epoch [1/3], Batch Loss: 0.1261
Epoch [1/3], Batch Loss: 0.2038
Epoch [1/3], Batch Loss: 0.1860
Epoch [1/3], Batch Loss: 0.1198
Epoch [1/3], Batch Loss: 0.1059
Epoch [1/3], Batch Loss: 0.0821
Epoch [1/3], Batch Loss: 0.1586
Epoch [1/3], Batch Loss: 0.1099
Epoch [1/3], Batch Loss: 0.1251
Epoch [1/3], Batch Loss: 0.1300
Epoch [1/3], Batch Loss: 0.1489
Epoch [1/3], Batch Loss: 0.1227
Epoch [1/3], Batch Loss: 0.0940
Epoch [1/3], Batch Loss: 0.1547
Epoch [1/3], Batch Loss: 0.1518
Epoch [1/3], Batch Loss: 0.1504
Epoch [1/3], Batch Loss: 0.1280
Epoch [1/3], Batch Loss: 0.1267
Epoch [1/3], Batch Loss: 0.1370
Epoch [1/3], Batch Loss: 0.1541
Epoch [1/3], Batch Loss: 0.1415
Epoch [1/3], Batch Loss: 0.1696
Epoch [1/3], Batch Loss: 0.1364
Epoch [1/3], Batch Loss: 0.1170
Epoch [1/3], Batch Loss: 0.1594
Epoch [1/3], Batch Loss: 0.1553
Epoch [1/3], Batch Loss: 0.1270
Epoch [1/3], Batch Loss: 0.1111
Epoch [1/3], Batch Loss: 0.1332
Epoch [1/3], Batch Loss: 0.1364
Epoch [1/3], Batch Loss: 0.0989
Epoch [1/3], Batch Loss: 0.1464
Epoch [1/3], Batch Loss: 0.1215
Epoch [1/3], Batch Loss: 0.0940
Epoch [1/3], Batch Loss: 0.1617
Epoch [1/3], Batch Loss: 0.1511
Epoch [1/3], Batch Loss: 0.0912
Epoch [1/3], Batch Loss: 0.1975
Epoch [1/3], Batch Loss: 0.1967
Epoch [1/3], Batch Loss: 0.1543
Epoch [1/3], Batch Loss: 0.1215
Epoch [1/3], Batch Loss: 0.1078
Epoch [1/3], Batch Loss: 0.1190
Epoch [1/3], Batch Loss: 0.0921
Epoch [1/3], Batch Loss: 0.1913
Epoch [1/3], Batch Loss: 0.1516
Epoch [1/3], Batch Loss: 0.1683
Epoch [1/3], Batch Loss: 0.1762
Epoch [1/3], Batch Loss: 0.1304
Epoch [1/3], Batch Loss: 0.1118
Epoch [1/3], Batch Loss: 0.0990
Epoch [1/3], Batch Loss: 0.1524
Epoch [1/3], Batch Loss: 0.1415
Epoch [1/3], Batch Loss: 0.1429
Epoch [1/3], Batch Loss: 0.1177
Epoch [1/3], Batch Loss: 0.1578
Epoch [1/3], Batch Loss: 0.0839
Epoch [1/3], Batch Loss: 0.1286
Epoch [1/3], Batch Loss: 0.1848
Epoch [1/3], Batch Loss: 0.1197
Epoch [1/3], Batch Loss: 0.1323
Epoch [1/3], Batch Loss: 0.0912
Epoch [1/3], Batch Loss: 0.1878
Epoch [1/3], Batch Loss: 0.1483
Epoch [1/3], Batch Loss: 0.1542
Epoch [1/3], Batch Loss: 0.0913
Epoch [1/3], Batch Loss: 0.1146
Epoch [1/3], Batch Loss: 0.1061
Epoch [1/3], Batch Loss: 0.1381
Epoch [1/3], Batch Loss: 0.1499
Epoch [1/3], Batch Loss: 0.0950
Epoch [1/3], Batch Loss: 0.1202
Epoch [1/3], Batch Loss: 0.1273
Epoch [1/3], Batch Loss: 0.1940
Epoch [1/3], Batch Loss: 0.1488
Epoch [1/3], Batch Loss: 0.1427
Epoch [1/3], Batch Loss: 0.1022
Epoch [1/3], Batch Loss: 0.1230
Epoch [1/3], Batch Loss: 0.1052
Epoch [1/3], Batch Loss: 0.1702
Epoch [1/3], Batch Loss: 0.1647
Epoch [1/3], Batch Loss: 0.1028
Epoch [1/3], Batch Loss: 0.1362
Epoch [1/3], Batch Loss: 0.1356
Epoch [1/3], Batch Loss: 0.0863
Epoch [1/3], Batch Loss: 0.1604
Epoch [1/3], Batch Loss: 0.0885
Epoch [1/3], Batch Loss: 0.0938
Epoch [1/3], Batch Loss: 0.1790
Epoch [1/3], Batch Loss: 0.1846
Epoch [1/3], Batch Loss: 0.1221
Epoch [1/3], Batch Loss: 0.1200
Epoch [1/3], Batch Loss: 0.1108
Epoch [1/3], Batch Loss: 0.1556
Epoch [1/3], Batch Loss: 0.1820
Epoch [1/3], Batch Loss: 0.1624
Epoch [1/3], Batch Loss: 0.1512
Epoch [1/3], Batch Loss: 0.0842
Epoch [1/3], Batch Loss: 0.1107
Epoch [1/3], Batch Loss: 0.1417
Epoch [1/3], Batch Loss: 0.1468
Epoch [1/3], Batch Loss: 0.1253
Epoch [1/3], Batch Loss: 0.1528
Epoch [1/3], Batch Loss: 0.1472
Epoch [1/3], Batch Loss: 0.1123
Epoch [1/3], Batch Loss: 0.1310
Epoch [1/3], Batch Loss: 0.0935
Epoch [1/3], Batch Loss: 0.1390
Epoch [1/3], Batch Loss: 0.1197
Epoch [1/3], Batch Loss: 0.1838
Epoch [1/3], Batch Loss: 0.1660
Epoch [1/3], Batch Loss: 0.1250
Epoch [1/3], Batch Loss: 0.1781
Epoch [1/3], Batch Loss: 0.1085
Epoch [1/3], Batch Loss: 0.1925
Epoch [1/3], Batch Loss: 0.1518
Epoch [1/3], Batch Loss: 0.1036
Epoch [1/3], Batch Loss: 0.1512
Epoch [1/3], Batch Loss: 0.0968
Epoch [1/3], Batch Loss: 0.1019
Epoch [1/3], Batch Loss: 0.0872
Epoch [1/3], Batch Loss: 0.1059
Epoch [1/3], Batch Loss: 0.1391
Epoch [1/3], Batch Loss: 0.0989
Epoch [1/3], Batch Loss: 0.1446
Epoch [1/3], Batch Loss: 0.1824
Epoch [1/3], Batch Loss: 0.1543
Epoch [1/3], Batch Loss: 0.1462
Epoch [1/3], Batch Loss: 0.1230
Epoch [1/3], Batch Loss: 0.1289
Epoch [1/3], Batch Loss: 0.1433
Epoch [1/3], Batch Loss: 0.1239
Epoch [1/3], Batch Loss: 0.0822
Epoch [1/3], Batch Loss: 0.1107
Epoch [1/3], Batch Loss: 0.0928
Epoch [1/3], Batch Loss: 0.1220
Epoch [1/3], Batch Loss: 0.1463
Epoch [1/3], Batch Loss: 0.1365
Epoch [1/3], Batch Loss: 0.1359
Epoch [1/3], Batch Loss: 0.1144
Epoch [1/3], Batch Loss: 0.1676
Epoch [1/3], Batch Loss: 0.1326
Epoch [1/3], Batch Loss: 0.1410
Epoch [1/3], Batch Loss: 0.1372
Epoch [1/3], Batch Loss: 0.1760
Epoch [1/3], Batch Loss: 0.1024
Epoch [1/3], Batch Loss: 0.1657
Epoch [1/3], Batch Loss: 0.1091
Epoch [1/3], Batch Loss: 0.1186
Epoch [1/3], Batch Loss: 0.1428
Epoch [1/3], Batch Loss: 0.1421
Epoch [1/3], Batch Loss: 0.1112
Epoch [1/3], Batch Loss: 0.1050
Epoch [1/3], Batch Loss: 0.1540
Epoch [1/3], Batch Loss: 0.1024
Epoch [1/3], Batch Loss: 0.1567
Epoch [1/3], Batch Loss: 0.1366
Epoch [1/3], Batch Loss: 0.1639
Epoch [1/3], Batch Loss: 0.1079
Epoch [1/3], Batch Loss: 0.0860
Epoch [1/3], Batch Loss: 0.1317
Epoch [1/3], Batch Loss: 0.1103
Epoch [1/3], Batch Loss: 0.1509
Epoch [1/3], Batch Loss: 0.1310
Epoch [1/3], Batch Loss: 0.1368
Epoch [1/3], Batch Loss: 0.0990
Epoch [1/3], Batch Loss: 0.1629
Epoch [1/3], Batch Loss: 0.1599
Epoch [1/3], Batch Loss: 0.1271
Epoch [1/3], Batch Loss: 0.1260
Epoch [1/3], Batch Loss: 0.1701
Epoch [1/3], Batch Loss: 0.1561
Epoch [1/3], Batch Loss: 0.1497
Epoch [1/3], Batch Loss: 0.0860
Epoch [1/3], Batch Loss: 0.1469
Epoch [1/3], Batch Loss: 0.1193
Epoch [1/3], Batch Loss: 0.1730
Epoch [1/3], Batch Loss: 0.1196
Epoch [1/3], Batch Loss: 0.1514
Epoch [1/3], Batch Loss: 0.2216
Epoch [1/3], Batch Loss: 0.1760
Epoch [1/3], Batch Loss: 0.1222
Epoch [1/3], Batch Loss: 0.1661
Epoch [1/3], Batch Loss: 0.1166
Epoch [1/3], Batch Loss: 0.1498
Epoch [1/3], Batch Loss: 0.1118
Epoch [1/3], Batch Loss: 0.1229
Epoch [1/3], Batch Loss: 0.1277
Epoch [1/3], Batch Loss: 0.1247
Epoch [1/3], Batch Loss: 0.1468
Epoch [1/3], Batch Loss: 0.1236
Epoch [1/3], Batch Loss: 0.1063
Epoch [1/3], Batch Loss: 0.0989
Epoch [1/3], Batch Loss: 0.1147
Epoch [1/3], Batch Loss: 0.1597
Epoch [1/3], Batch Loss: 0.0890
Epoch [1/3], Batch Loss: 0.1174
Epoch [1/3], Batch Loss: 0.1151
Epoch [1/3], Batch Loss: 0.1128
Epoch [1/3], Batch Loss: 0.0983
Epoch [1/3], Batch Loss: 0.1229
Epoch [1/3], Batch Loss: 0.0565
Epoch [1/3], Batch Loss: 0.0880
Epoch [1/3], Batch Loss: 0.1426
Epoch [1/3], Batch Loss: 0.1525
Epoch [1/3], Batch Loss: 0.1052
Epoch [1/3], Batch Loss: 0.1093
Epoch [1/3], Batch Loss: 0.0904
Epoch [1/3], Batch Loss: 0.1345
Epoch [1/3], Batch Loss: 0.0952
Epoch [1/3], Batch Loss: 0.1263
Epoch [1/3], Batch Loss: 0.1479
Epoch [1/3], Batch Loss: 0.0920
Epoch [1/3], Batch Loss: 0.1354
Epoch [1/3], Batch Loss: 0.0888
Epoch [1/3], Batch Loss: 0.1665
Epoch [1/3], Batch Loss: 0.1318
Epoch [1/3], Batch Loss: 0.1422
Epoch [1/3], Batch Loss: 0.1084
Epoch [1/3], Batch Loss: 0.1670
Epoch [1/3], Batch Loss: 0.0692
Epoch [1/3], Batch Loss: 0.1219
Epoch [1/3], Batch Loss: 0.1239
Epoch [1/3], Batch Loss: 0.1028
Epoch [1/3], Batch Loss: 0.1006
Epoch [1/3], Batch Loss: 0.1282
Epoch [1/3], Batch Loss: 0.1396
Epoch [1/3], Batch Loss: 0.1509
Epoch [1/3], Batch Loss: 0.1874
Epoch [1/3], Batch Loss: 0.1656
Epoch [1/3], Batch Loss: 0.1010
Epoch [1/3], Batch Loss: 0.1308
Epoch [1/3], Batch Loss: 0.0974
Epoch [1/3], Batch Loss: 0.1672
Epoch [1/3], Batch Loss: 0.1218
Epoch [1/3], Batch Loss: 0.0822
Epoch [1/3], Batch Loss: 0.2161
Epoch [1/3], Batch Loss: 0.1067
Epoch [1/3], Batch Loss: 0.1023
Epoch [1/3], Batch Loss: 0.1291
Epoch [1/3], Batch Loss: 0.1136
Epoch [1/3], Batch Loss: 0.1307
Epoch [1/3], Batch Loss: 0.1480
Epoch [1/3], Batch Loss: 0.1117
Epoch [1/3], Batch Loss: 0.1087
Epoch [1/3], Batch Loss: 0.1597
Epoch [1/3], Batch Loss: 0.1126
Epoch [1/3], Batch Loss: 0.1125
Epoch [1/3], Batch Loss: 0.1362
Epoch [1/3], Batch Loss: 0.1042
Epoch [1/3], Batch Loss: 0.1383
Epoch [1/3], Batch Loss: 0.1426
Epoch [1/3], Batch Loss: 0.1520
Epoch [1/3], Batch Loss: 0.0975
Epoch [1/3], Batch Loss: 0.1112
Epoch [1/3], Batch Loss: 0.0794
Epoch [1/3], Batch Loss: 0.1965
Epoch [1/3], Batch Loss: 0.1119
Epoch [1/3], Batch Loss: 0.1184
Epoch [1/3], Batch Loss: 0.1178
Epoch [1/3], Batch Loss: 0.1273
Epoch [1/3], Batch Loss: 0.1016
Epoch [1/3], Batch Loss: 0.1409
Epoch [1/3], Batch Loss: 0.1544
Epoch [1/3], Batch Loss: 0.0825
Epoch [1/3], Batch Loss: 0.1117
Epoch [1/3], Batch Loss: 0.1279
Epoch [1/3], Batch Loss: 0.1347
Epoch [1/3], Batch Loss: 0.1023
Epoch [1/3], Batch Loss: 0.1181
Epoch [1/3], Batch Loss: 0.1251
Epoch [1/3], Batch Loss: 0.1450
Epoch [1/3], Batch Loss: 0.1384
Epoch [1/3], Batch Loss: 0.1521
Epoch [1/3], Batch Loss: 0.0688
Epoch [1/3], Batch Loss: 0.1197
Epoch [1/3], Batch Loss: 0.1180
Epoch [1/3], Batch Loss: 0.1128
Epoch [1/3], Batch Loss: 0.0623
Epoch [1/3], Batch Loss: 0.1225
Epoch [1/3], Batch Loss: 0.1492
Epoch [1/3], Batch Loss: 0.1176
Epoch [1/3], Batch Loss: 0.1205
Epoch [1/3], Batch Loss: 0.1045
Epoch [1/3], Batch Loss: 0.1565
Epoch [1/3], Batch Loss: 0.1290
Epoch [1/3], Batch Loss: 0.1395
Epoch [1/3], Batch Loss: 0.1328
Epoch [1/3], Batch Loss: 0.1237
Epoch [1/3], Batch Loss: 0.1142
Epoch [1/3], Batch Loss: 0.0980
Epoch [1/3], Batch Loss: 0.1610
Epoch [1/3], Batch Loss: 0.1578
Epoch [1/3], Batch Loss: 0.1439
Epoch [1/3], Batch Loss: 0.1297
Epoch [1/3], Batch Loss: 0.1284
Epoch [1/3], Batch Loss: 0.1731
Epoch [1/3], Batch Loss: 0.0888
Epoch [1/3], Batch Loss: 0.1068
Epoch [1/3], Batch Loss: 0.1116
Epoch [1/3], Batch Loss: 0.1139
Epoch [1/3], Batch Loss: 0.0992
Epoch [1/3], Batch Loss: 0.1412
Epoch [1/3], Batch Loss: 0.1066
Epoch [1/3], Batch Loss: 0.1213
Epoch [1/3], Batch Loss: 0.1190
Epoch [1/3], Batch Loss: 0.1147
Epoch [1/3], Batch Loss: 0.1174
Epoch [1/3], Batch Loss: 0.1095
Epoch [1/3], Batch Loss: 0.1074
Epoch [1/3], Batch Loss: 0.0923
Epoch [1/3], Batch Loss: 0.1267
Epoch [1/3], Batch Loss: 0.0907
Epoch [1/3], Batch Loss: 0.1093
Epoch [1/3], Batch Loss: 0.1353
Epoch [1/3], Batch Loss: 0.1145
Epoch [1/3], Batch Loss: 0.0698
Epoch [1/3], Batch Loss: 0.1199
Epoch [1/3], Batch Loss: 0.1269
Epoch [1/3], Batch Loss: 0.1139
Epoch [1/3], Batch Loss: 0.1117
Epoch [1/3], Batch Loss: 0.0998
Epoch [1/3], Batch Loss: 0.1433
Epoch [1/3], Batch Loss: 0.0543
Epoch [1/3], Batch Loss: 0.1060
Epoch [1/3], Batch Loss: 0.0847
Epoch [1/3], Batch Loss: 0.0819
Epoch [1/3], Batch Loss: 0.0913
Epoch [1/3], Batch Loss: 0.0530
Epoch [1/3], Batch Loss: 0.0985
Epoch [1/3], Batch Loss: 0.0855
Epoch [1/3], Batch Loss: 0.1170
Epoch [1/3], Batch Loss: 0.1221
Epoch [1/3], Batch Loss: 0.1508
Epoch [1/3], Batch Loss: 0.1431
Epoch [1/3], Batch Loss: 0.1304
Epoch [1/3], Batch Loss: 0.1360
Epoch [1/3], Batch Loss: 0.1149
Epoch [1/3], Batch Loss: 0.0883
Epoch [1/3], Batch Loss: 0.1156
Epoch [1/3], Batch Loss: 0.1128
Epoch [1/3], Batch Loss: 0.1346
Epoch [1/3], Batch Loss: 0.1171
Epoch [1/3], Batch Loss: 0.0809
Epoch [1/3], Batch Loss: 0.1094
Epoch [1/3], Batch Loss: 0.0929
Epoch [1/3], Batch Loss: 0.1210
Epoch [1/3], Batch Loss: 0.0714
Epoch [1/3], Batch Loss: 0.0935
Epoch [1/3], Batch Loss: 0.0546
Epoch [1/3], Batch Loss: 0.0832
Epoch [1/3], Batch Loss: 0.1045
Epoch [1/3], Batch Loss: 0.0629
Epoch [1/3], Batch Loss: 0.0884
Epoch [1/3], Batch Loss: 0.1392
Epoch [1/3], Batch Loss: 0.1193
Epoch [1/3], Batch Loss: 0.0918
Epoch [1/3], Batch Loss: 0.1226
Epoch [1/3], Batch Loss: 0.1083
Epoch [1/3], Batch Loss: 0.1303
Epoch [1/3], Batch Loss: 0.1104
Epoch [1/3], Batch Loss: 0.0771
Epoch [1/3], Batch Loss: 0.0616
Epoch [1/3], Batch Loss: 0.1229
Epoch [1/3], Batch Loss: 0.1568
Epoch [1/3], Batch Loss: 0.1206
Epoch [1/3], Batch Loss: 0.0906
Epoch [1/3], Batch Loss: 0.0880
Epoch [1/3], Batch Loss: 0.0819
Epoch [1/3], Batch Loss: 0.1209
Epoch [1/3], Batch Loss: 0.0903
Epoch [1/3], Batch Loss: 0.0980
Epoch [1/3], Batch Loss: 0.1363
Epoch [1/3], Batch Loss: 0.1571
Epoch [1/3], Batch Loss: 0.1210
Epoch [1/3], Batch Loss: 0.0861
Epoch [1/3], Batch Loss: 0.0880
Epoch [1/3], Batch Loss: 0.1073
Epoch [1/3], Batch Loss: 0.1012
Epoch [1/3], Batch Loss: 0.1012
Epoch [1/3], Batch Loss: 0.0733
Epoch [1/3], Batch Loss: 0.0688

In [1]:
import pickle

In [ ]:
# Save the model to a .pkl file
torch.save(model.state_dict(), 'model.pkl')

In [30]:
# Load the saved model from file
state_dict = torch.load('/content/model.pkl')

# Load the state dict into the model
model.load_state_dict(state_dict)

In [ ]:
test_df

                      id                                       comment_text
0       00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1       0000247867823ef7  == From RfC == \n\n The title is fine as it is...
2       00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3       00017563c3f7919a  :If you have a look back at the source, the in...
4       00017695ad8997eb          I don't anonymously edit articles at all.
...                  ...                                                ...
153159  fffcd0960ee309b5  . \n i totally agree, this stuff is nothing bu...
153160  fffd7a9a6eb32c16  == Throw from out field to home plate. == \n\n...
153161  fffda9e8d6fafa9e  " \n\n == Okinotorishima categories == \n\n I ...
153162  fffe8f1340a79fc2  " \n\n == ""One of the founding nations of the...
153163  ffffce3fb183ee80  " \n :::Stop already. Your bullshit is not wel...

[153164 rows x 2 columns]

In [55]:
submission_df=pd.read_csv('/content/sample_submission.csv')
submission_df

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,00001cee341fdb12,0.5,0.5,0.5,0.5,0.5,0.5
1,0000247867823ef7,0.5,0.5,0.5,0.5,0.5,0.5
2,00013b17ad220c46,0.5,0.5,0.5,0.5,0.5,0.5
3,00017563c3f7919a,0.5,0.5,0.5,0.5,0.5,0.5
4,00017695ad8997eb,0.5,0.5,0.5,0.5,0.5,0.5
...,...,...,...,...,...,...,...
153159,fffcd0960ee309b5,0.5,0.5,0.5,0.5,0.5,0.5
153160,fffd7a9a6eb32c16,0.5,0.5,0.5,0.5,0.5,0.5
153161,fffda9e8d6fafa9e,0.5,0.5,0.5,0.5,0.5,0.5
153162,fffe8f1340a79fc2,0.5,0.5,0.5,0.5,0.5,0.5
153163,ffffce3fb183ee80,0.5,0.5,0.5,0.5,0.5,0.5

In [65]:
# Make predictions on the test dataset
model.eval()  # Set model to evaluation mode
test_probs = []
with torch.no_grad():
    for batch in test_dl:
        # Move data to GPU if available
        inputs = batch[0].to(device)

        # Forward pass
        outputs = model(inputs)

        # Calculate probabilities using sigmoid activation
        probs = torch.sigmoid(outputs)

        # Append probabilities to the list
        test_probs.append(probs)

# Concatenate probabilities from all batches
test_probs = torch.cat(test_probs)

# Convert probabilities to numpy array and assign to submission dataframe
submission_df[target_cols] = test_probs.detach().cpu().numpy()

# Save submission dataframe to CSV file
submission_df.to_csv('submission.csv', index=None)

In [66]:
submission_result_df=pd.read_csv('submission.csv')
submission_result_df

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,00001cee341fdb12,0.993809,3.217910e-01,0.975901,0.051884,0.870420,0.200248
1,0000247867823ef7,0.001030,2.427304e-06,0.000202,0.000008,0.000090,0.000038
2,00013b17ad220c46,0.000585,2.599704e-06,0.000107,0.000012,0.000051,0.000025
3,00017563c3f7919a,0.000275,8.904606e-07,0.000064,0.000004,0.000027,0.000012
4,00017695ad8997eb,0.000479,1.465778e-06,0.000087,0.000007,0.000035,0.000013
...,...,...,...,...,...,...,...
153159,fffcd0960ee309b5,0.001055,3.176159e-06,0.000156,0.000014,0.000076,0.000027
153160,fffd7a9a6eb32c16,0.002258,5.056394e-06,0.000319,0.000023,0.000216,0.000101
153161,fffda9e8d6fafa9e,0.000368,1.181667e-06,0.000106,0.000005,0.000039,0.000021
153162,fffe8f1340a79fc2,0.003387,4.251925e-06,0.000533,0.000024,0.000280,0.000081
153163,ffffce3fb183ee80,0.954220,1.274685e-02,0.439612,0.019423,0.454209,0.036235

In [5]:
test_labels_df=pd.read_csv('test_labels.csv')

In [6]:
test_labels_df

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,00001cee341fdb12,-1,-1,-1,-1,-1,-1
1,0000247867823ef7,-1,-1,-1,-1,-1,-1
2,00013b17ad220c46,-1,-1,-1,-1,-1,-1
3,00017563c3f7919a,-1,-1,-1,-1,-1,-1
4,00017695ad8997eb,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...
153159,fffcd0960ee309b5,-1,-1,-1,-1,-1,-1
153160,fffd7a9a6eb32c16,-1,-1,-1,-1,-1,-1
153161,fffda9e8d6fafa9e,-1,-1,-1,-1,-1,-1
153162,fffe8f1340a79fc2,-1,-1,-1,-1,-1,-1
153163,ffffce3fb183ee80,-1,-1,-1,-1,-1,-1

In [7]:
filtered_df = test_labels_df[(test_labels_df.iloc[:, 2:] != -1).all(axis=1)]

In [8]:
filtered_df

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
5,0001ea8717f6de06,0,0,0,0,0,0
7,000247e83dcc1211,0,0,0,0,0,0
11,0002f87b16116a7f,0,0,0,0,0,0
13,0003e1cccfd5a40a,0,0,0,0,0,0
14,00059ace3e3e9a53,0,0,0,0,0,0
...,...,...,...,...,...,...,...
153150,fff8f64043129fa2,0,0,0,0,0,0
153151,fff9d70fe0722906,0,0,0,0,0,0
153154,fffa8a11c4378854,0,0,0,0,0,0
153155,fffac2a094c8e0e2,1,0,1,0,1,0
153156,fffb5451268fb5ba,0,0,0,0,0,0

In [49]:
# Make predictions on the test dataset
model.eval()  # Set model to evaluation mode
predicted_labels = []
with torch.no_grad():
    for batch in test_dl:
        # Move data to GPU if available
        inputs = batch[0].to(device)

        # Forward pass
        outputs = model(inputs)

        # Convert outputs to binary predictions
        binary_predictions = (outputs > 0.5).int()

        # Append binary predictions to the list
        predicted_labels.append(binary_predictions)

# Concatenate binary predictions from all batches
predicted_labels = torch.cat(predicted_labels)

# Convert binary predictions to numpy array
predicted_labels = predicted_labels.detach().cpu().numpy()

# Combine the true labels and predicted labels for each label into a single DataFrame
result_df = test_df[['comment_text']].copy()  # Copy comment_text column from test_df
for label in ['toxic', 'severe_toxic', 'threat', 'obscene', 'insult', 'identity_hate']:
    # Concatenate true labels and predicted labels for each label
    result_df[label + '_true'] = test_labels_df[label]
    result_df[label + '_predicted'] = predicted_labels[:, target_cols.index(label)]

# Save the result DataFrame to a CSV file
result_df.to_csv('result.csv', index=False)

/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(

In [50]:
result_df

,comment_text,toxic_true,toxic_predicted,severe_toxic_true,severe_toxic_predicted,threat_true,threat_predicted,obscene_true,obscene_predicted,insult_true,insult_predicted,identity_hate_true,identity_hate_predicted
0,Yo bitch Ja Rule is more succesful then you'll...,-1,1,-1,0,-1,0,-1,1,-1,1,-1,0
1,== From RfC == \n\n The title is fine as it is...,-1,0,-1,0,-1,0,-1,0,-1,0,-1,0
2,""" \n\n == Sources == \n\n * Zawe Ashton on Lap...",-1,0,-1,0,-1,0,-1,0,-1,0,-1,0
3,":If you have a look back at the source, the in...",-1,0,-1,0,-1,0,-1,0,-1,0,-1,0
4,I don't anonymously edit articles at all.,-1,0,-1,0,-1,0,-1,0,-1,0,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
142297,". \n i totally agree, this stuff is nothing bu...",0,0,0,0,0,0,0,0,0,0,0,0
142298,== Throw from out field to home plate. == \n\n...,-1,0,-1,0,-1,0,-1,0,-1,0,-1,0
142299,""" \n\n == Okinotorishima categories == \n\n I ...",-1,0,-1,0,-1,0,-1,0,-1,0,-1,0
142300,""" \n\n == """"One of the founding nations of the...",0,0,0,0,0,0,0,0,0,0,0,0
142301,""" \n :::Stop already. Your bullshit is not wel...",-1,1,-1,0,-1,0,-1,0,-1,0,-1,0

In [52]:
# remove the '-1' values
filtered_df = result_df[(result_df.iloc[:, 1:] != -1).all(axis=1)]

# Print the filtered DataFrame
print(filtered_df)

                                             comment_text  toxic_true  \
5       Thank you for understanding. I think very high...           0
7                        :Dear god this site is horrible.           0
11      "::: Somebody will invariably try to add Relig...           0
13      " \n\n It says it right there that it IS a typ...           0
14      " \n\n == Before adding a new product to the l...           0
...                                                   ...         ...
142287  shut down the mexican border withought looking...           0
142291  " \n\n ==""Illness"" no shit== \n Just for the...           0
142294  " \n\n == Unicorn lair discovery == \n\n Suppo...           0
142297  . \n i totally agree, this stuff is nothing bu...           0
142300  " \n\n == ""One of the founding nations of the...           0

        toxic_predicted  severe_toxic_true  severe_toxic_predicted  \
5                     0                  0                       0
7                     0                  0                       0
11                    0                  0                       0
13                    0                  0                       0
14                    0                  0                       0
...                 ...                ...                     ...
142287                0                  0                       0
142291                1                  0                       0
142294                0                  0                       0
142297                0                  0                       0
142300                0                  0                       0

        threat_true  threat_predicted  obscene_true  obscene_predicted  \
5                 0                 0             0                  0
7                 0                 0             0                  0
11                0                 0             0                  0
13                0                 0             0                  0
14                0                 0             0                  0
...             ...               ...           ...                ...
142287            0                 0             0                  0
142291            0                 0             0                  1
142294            0                 0             0                  0
142297            0                 0             0                  0
142300            0                 0             0                  0

        insult_true  insult_predicted  identity_hate_true  \
5                 0                 0                   0
7                 0                 0                   0
11                0                 0                   0
13                0                 0                   0
14                0                 0                   0
...             ...               ...                 ...
142287            0                 0                   0
142291            0                 0                   0
142294            0                 0                   0
142297            0                 0                   0
142300            0                 0                   0

        identity_hate_predicted
5                             0
7                             0
11                            0
13                            0
14                            0
...                         ...
142287                        0
142291                        0
142294                        0
142297                        0
142300                        0

[59541 rows x 13 columns]

In [54]:
# Write the filtered DataFrame to a CSV file
filtered_df.to_csv('results_gt_pred.csv', index=False)

In [53]:
# Calculate accuracy for each label
accuracies = {}
for label in ['toxic', 'severe_toxic', 'threat', 'obscene', 'insult', 'identity_hate']:
    # Calculate accuracy for the label
    correct_predictions = (filtered_df[label + '_true'] == filtered_df[label + '_predicted']).sum()
    total_predictions = len(filtered_df)
    accuracy = correct_predictions / total_predictions
    accuracies[label] = accuracy

# Print accuracies
for label, accuracy in accuracies.items():
    print("Accuracy for {}: {:.4f}".format(label, accuracy))

Accuracy for toxic: 0.7749
Accuracy for severe_toxic: 0.9934
Accuracy for threat: 0.9968
Accuracy for obscene: 0.8665
Accuracy for insult: 0.8863
Accuracy for identity_hate: 0.9889

In [67]:
# Calculate combined accuracy
combined_accuracy = np.mean(list(accuracies.values()))

# Print accuracies
print("Combined Accuracy: {:.4f}".format(combined_accuracy))

Combined Accuracy: 0.9178